apiVersion: v1
kind: Secret
metadata:
  name: custom-certificates
  labels:
    argocd.argoproj.io/secret-type: repository
    {{- include "argo-cd.labels" (dict "context" $) | nindent 4 }}
data:
  {{- range $key, $value := .Values.configs.customCertificates }}
  {{ $key }}: {{ $value | toString | b64enc }}
  {{- end }}
